#UTILIZZO DATABASE
USE AdventureWorksDW;
#MOSTRA TABELLE
SHOW TABLES;

#1. SCRIVI UNA QUERY PER VERIFICARE CHE IL CAMPO PRODUCTKEY NELLA TABELLA DIMPRODUCT SIA UNA PK
#PK E' UNIVOCA E MAI NULLA, QUINDI QUESTE DUE CONDIZIONI DEVONO ESSERE VERE

#ESERCIZIO
SELECT DISTINCT ProductKey
FROM dimproduct; 
#CAMPO UNIVOCO PERCHE' SIA CON DISTINCT CHE SENZA DISTINC SONO 606 RIGHE

SELECT ProductKey
FROM dimproduct
WHERE ProductKey IS NULL;
#NON CI SONO CAMPI NULL

#SECONDO METODO PER VERIFICARE CHE PRODUCT KEY SIA UNA PK: A SINISTRA SELEZIONARE 
#NEGLI SCHEMAS DIMPRODUCT E IN INFORMATION COMPARIRA' PK ACCANTO PRODUCT KEY

SELECT ProductKey, COUNT(*)
FROM dimproduct
GROUP BY ProductKey
HAVING COUNT(*)>1;
#TERZO METODO PER VERIFICARE CHE LA PRODUCT KEY SIA PK

#2. SCRIVI UNA QUERY PER VERIFICARE CHE LA COMBINAZIONE DEI CAMPI SALESORDERNUMBER 
#E SALESORDERLINENUMBER SIA UNA PK

#ESERCIZIO
SELECT SalesOrderNumber, SalesOrderLineNumber, COUNT(*) AS Conteggio
FROM factresellersales
GROUP BY SalesOrderNumber, SalesOrderLineNumber
HAVING COUNT(*)>1;

SELECT SalesOrderNumber, SalesOrderLineNumber, COUNT(*) AS Conteggio
FROM factresellersales
WHERE SalesOrderNumber IS NULL AND SalesOrderLineNumber IS NULL
GROUP BY SalesOrderNumber, SalesOrderLineNumber;


#3. CONTA IL NUMERO TRANSAZIONI (SALESORDERLINENUMBER) REALIZZATE OGNI GIORNO A PARTIRE DAL 1 GENNAIO 2020

#DETTAGLIO DI FACT RESELLER SALES
DESCRIBE factresellersales;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM factresellersales;

#ESERCIZIO
SELECT SalesOrderNumber, COUNT(SalesOrderLineNumber) AS NumeroTransazioni, OrderDate
FROM factresellersales
WHERE OrderDate>='2020-01-01'
GROUP BY OrderDate;

#4. CALCOLA IL FATTURATO TOTALE (FACTRESELLERSALES.SALESAMOUNT), LA QUANTITA' TOTALE VENDUTA (FACTRESELLERSALES.ORDERQUANTITY)
#E IL PREZZO MEDIO DI VENDITA (FACTRESELLERSALES.UNITPRICE) PER PRODOTTO (DIMPRODUCT) A PARTIRE DAL 1 GENNAIO 2020.
#IL RESULT SET DEVE ESPORRE IL NOME DEL PRODOTTO, IL FATTURATO TOTALE, LA QUANTITA' TOTALE VENDUTA E IL PREZZO MEDIO DI VENDITA

#DETTAGLIO DI FACT RESELLER SALES
DESCRIBE factresellersales;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM factresellersales;

#DETTAGLIO DI DIM PRODUCT
DESCRIBE dimproduct;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM dimproduct;

#ESERCIZIO
SELECT  P.EnglishProductName AS NomeProdotto, S.OrderDate, SUM(S.SalesAmount) AS TotaleFatturato, 
		SUM(S.OrderQuantity) AS TotaleQuantita, AVG(S.UnitPrice) AS PrezzoMedio
FROM factresellersales AS S INNER JOIN dimproduct AS P 
ON S.ProductKey = P.ProductKey
WHERE S.OrderDate>='2020-01-01'
GROUP BY P.EnglishProductName;

#5. CALCOLA IL FATTURATO TOTALE (FACTRESELLERSALES.SALESAMOUNT), LA QUANTITA' TOTALE VENDUTA (FACTRESELLERSALES.ORDERQUANTITY)
#PER CATEGORIA PRODOTTO (DIMPRODUCTCATEGORY).
#IL RESULT SET DEVE ESPORRE IL NOME DELLA CATEGORIA, IL FATTURATO TOTALE E LA QUANTITA' TOTALE VENDUTA

#DETTAGLIO DI FACT RESELLER SALES
DESCRIBE factresellersales;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM factresellersales;

#DETTAGLIO DI DIM PRODUCT
DESCRIBE dimproduct;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM dimproduct;

#DETTAGLIO DI DIM PRODUCT SUBCATEGORY
DESCRIBE dimproductsubcategory;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM dimproductsubcategory;

#DETTAGLIO DI DIM PRODUCT CATEGORY
DESCRIBE dimproductcategory;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM dimproductcategory;

#ESERCIZIO
SELECT  C.EnglishProductCategoryName AS NomeCategoria, SUM(S.SalesAmount) AS TotaleFatturato,
		SUM(S.OrderQuantity) AS TotaleQuantita
FROM factresellersales AS S INNER JOIN dimproduct AS P
	 ON S.ProductKey = P.ProductKey
                            INNER JOIN dimproductsubcategory AS SC
	 ON P.ProductSubcategoryKey = SC.ProductSubcategoryKey
							INNER JOIN dimproductcategory AS C
	 ON SC.ProductCategoryKey = C.ProductCategoryKey
GROUP BY C.EnglishProductCategoryName;


#6. CALCOLA IL FATTURATO TOTALE PER AREA CITTA' (DIMGEOGRAPHY.CITY) REALIZZATO A PARTIRE DAL 1 GENNAIO 2020
#IL RESULT SET DEVE ESPORRE L'ELENCO DELLE CITTA' CON FATTURATO REALIZZATO SUPERIORE A 60K

#DETTAGLIO DI FACT RESELLER SALES
DESCRIBE factresellersales;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM factresellersales;

#DETTAGLIO DI DIM RESELLER
DESCRIBE dimreseller;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM dimreseller; 
#GEOGRAPHYKEY - FK / RESELLERKEY - PK

#DETTAGLIO DIM GEOGRAPHY
DESCRIBE dimgeography;
#VISUALIZZO GLI ELEMENTI 
SELECT * FROM dimgeography; 
#GEOGRAPHYKEY PK

#ESERCIZIO
SELECT G.City AS Citta, SUM(S.SalesAmount) AS TotaleFatturato
FROM dimgeography AS G INNER JOIN dimreseller AS R
     ON G.GeographyKey = R.GeographyKey
					   INNER JOIN factresellersales AS S 
	 ON S.ResellerKey = R.ResellerKey                 
WHERE S.OrderDate>='2020-01-01'
GROUP BY G.City
HAVING SUM(S.SalesAmount)>60000;